### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by edcasati** [joepuzzo/robot-viewer#4]
For those of us not versed in the voodoo magic of Linux, can you explain how to install?
I tried my best, only making things worse as I tried to get it going.
Thanks... it looks wonderful, going to try running it with an AR4.

**Comment by joepuzzo** [comment]
Are you on a mac ? I run this on my macbook not on linux. All the info on how to get started is in the README

**Comment by joepuzzo** [comment]
Also please note that to get this running with AR4 you also need this code https://github.com/joepuzzo/servo

**Comment by edcasati** [comment]
On a PC running Ubuntu in a VMware instance.

Where should I unzip the files to?
I had to upgrade the Node.js stuff to V14+




________________________________

**Comment by joepuzzo** [comment]
I would use at least node 16 and also you can unzip anywhere. This library kind of assumes some programming knowledge so apologies if the README did not make sense to you.

**Comment by edcasati** [comment]
OK! I made sense of the README file and got it working>
I had not created the two folders in /src. I thought that it meant that it uses the two folders that it will be creating itself.
If I may make a suggestion, add/change the instructions to:
"The program uses the following two folders that you need to create in /usr/local/src "
